/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package duan1_nhom1.view;

import duan1_nhom1.dto.ChiTietHoaDonDto;
import duan1_nhom1.dto.ChiTietSanPhamDto;
import duan1_nhom1.dto.HoaDonDto;
import duan1_nhom1.dto.SanPhamDto;
import duan1_nhom1.model.Khach;
import duan1_nhom1.service.ChiTietHoaDonService;
import duan1_nhom1.service.HoaDonService;
import duan1_nhom1.service.KhachService;
import duan1_nhom1.service.SanPhamService;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maccuacu
 */
public class HoaDonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HoaDonJPanel
     */
    private DefaultTableModel dtm = new DefaultTableModel();

    private HoaDonService hds = new HoaDonService();

    private KhachService ks = new KhachService();

    private HoaDonDto hd = new HoaDonDto();
    private ChiTietHoaDonService ctService = new ChiTietHoaDonService();
    private HoaDonService hdService = new HoaDonService();
    private SanPhamService spService = new SanPhamService();

    private DefaultTableModel dtmCt = new DefaultTableModel();

    ChiTietSanPhamDto chiTietSanPhamDto = new ChiTietSanPhamDto();
    
    HoaDonDto donDto = new HoaDonDto();

    public HoaDonJPanel() {
        initComponents();
        this.loadTable();
//        this.loadCbbKhack();
    }

//    public void loadCbbKhack() {
//        for (Khach khach : ks.getAll()) {
//            KhachCbb.addItem(khach.getSdt());
//        }
//    }
    public void loadTable() {
        dtm = (DefaultTableModel) tblHoaDon.getModel();
        dtm.setRowCount(0);
        int count = 0;

        for (HoaDonDto hd : hds.getAll()) {
            String status;
            if (hd.getTrangThai()) {
                status = "Đã thanh toán";
            } else {
                status = "Chưa thanh toán";
            }
            Khach k = ks.findById(hd.getIdKhachHang());
            String tenK = "";
            if (k!=null) {
               tenK = k.getTenKhachHang();

            }

            Object[] rowData = {
                ++count,
                hd.getId(),
                k == null ? "": tenK,
                "",
                hd.getIdNv(),
                hd.getMa(),
                hd.getTongTien(),
                hd.getNgayMua(),
                hd.getNgayTao(),
                hd.getNgaySua(),
                status
            };
            dtm.addRow(rowData);

        }
    }

    private void loadTableCTHD(HoaDonDto hd) {
        
        if (hd == null) {
            return;
        }
        dtmCt = (DefaultTableModel) this.tblHDCT1.getModel();
        dtmCt.setRowCount(0);
        int count = 0;

        for (ChiTietHoaDonDto cthd : this.ctService.getAllByIdHd(hd.getId())) {
            HoaDonDto hdto = this.hdService.findById(hd.getId());
            SanPhamDto spdto = this.spService.findById(cthd.getIdSP());
            String status;
            if (cthd.getTrangThai()) {
                status = "Đã thanh toán";
            } else {
                status = "Chưa thanh toán";
            }
            Object[] rowData = {
                ++count,
                hdto.getMa(),
                spdto.getMa(),
                cthd.getSoLuong(),
                cthd.getGiaBan(),
                status
            };
            dtmCt.addRow(rowData);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        show = new javax.swing.JButton();
        btnCTHD = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHDCT1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(203, 233, 162));

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID", "Tên khách", "Số điện thoại khách", "ID Nhân viên", "Mã hoá đơn", "Tổng tiền", "Ngày mua", "Ngày tạo", "Ngày sửa", "Trạng thái"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        show.setText("Hiển thị");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        btnCTHD.setText("Chi Tiết Hoá Đơn");
        btnCTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTHDActionPerformed(evt);
            }
        });

        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        tblHDCT1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Mã hoá đơn", "Mã sản phẩm", "Số lượng", "Giá bán", "Trạng thái"
            }
        ));
        tblHDCT1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHDCT1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblHDCT1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1357, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(show))
                            .addComponent(btnCTHD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(show)
                        .addGap(18, 18, 18)
                        .addComponent(btnCTHD)
                        .addGap(0, 306, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showActionPerformed

    private void btnCTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTHDActionPerformed
        // TODO add your handling code here:
        loadTableCTHD(donDto);
    }//GEN-LAST:event_btnCTHDActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:

        int index = -1;
        index = this.tblHoaDon.getSelectedRow();
        if (index == -1) {
            return;
        }
        
        donDto = hdService.findById(this.tblHoaDon.getValueAt(index, 1).toString());
                 dtmCt.setRowCount(0);


    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void tblHDCT1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHDCT1MouseClicked
        // TODO add your handling code here:
//        int index = -1;
//        index = this.tblHDCT.getSelectedRow();
//
//        if (index == -1) {
//            return;
//        }
//
//        txtMạHd.setText(this.tblHDCT.getValueAt(index, 1).toString());
//        txtMaSp.setText(this.tblHDCT.getValueAt(index, 2).toString());
//        txtSoLuong.setText(this.tblHDCT.getValueAt(index, 3).toString());
//        txtGiaBan.setText(this.tblHDCT.getValueAt(index, 4).toString());
//        String status = this.tblHDCT.getValueAt(index, 5).toString();
//        if (status.equals("Đã thanh toán")) {
//            rd1.setSelected(true);
//        } else {
//            rd0.setSelected(true);
//        }
//        chiTietSanPhamDto.setMa(this.tblHDCT.getValueAt(index, 2).toString());
    }//GEN-LAST:event_tblHDCT1MouseClicked

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jScrollPane3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCTHD;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton show;
    private javax.swing.JTable tblHDCT1;
    private javax.swing.JTable tblHoaDon;
    // End of variables declaration//GEN-END:variables
}
